server:
  port: 8770
dubbo:
  application:
    name: d_provider
  registry:
    address: nacos://localhost:8848
    group: example
    parameters:
      namespace: 288e804d-c89b-4745-9eef-f0310d9025b2
  provider:
    cluster: example
    filter: tracing
  consumer:
    cluster: example
    filter: tracing

spring:
  application:
    name: d_provider
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 288e804d-c89b-4745-9eef-f0310d9025b2
        group: example
        cluster-name: example
  sleuth:
    sampler:
      rate: 100
  zipkin:
    base-url: http://localhost:9411/