server:
  ssl:
    key-store: D:/keys/jc.key
    key-store-password: 123456
    key-password: 123456
  port: 9000

spring:
  datasource:
    username: crmuser
    password: crmuser
    url: jdbc:mysql://10.1.21.56:3306/oauth2?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true