server:
  port: 9000

spring:
  datasource:
    username: root
    password: qQ598885407
    url: jdbc:mysql://192.168.31.198:3306/oauth2?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true